/********************************************************************
* lib/PlutoCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error lib/PlutoCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablePlutoCint();
extern void G__cpp_setup_inheritancePlutoCint();
extern void G__cpp_setup_typetablePlutoCint();
extern void G__cpp_setup_memvarPlutoCint();
extern void G__cpp_setup_globalPlutoCint();
extern void G__cpp_setup_memfuncPlutoCint();
extern void G__cpp_setup_funcPlutoCint();
extern void G__set_cpp_environmentPlutoCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "src/PAdaptiveMesh.h"
#include "src/PAdaptiveMeshN.h"
#include "src/PAngularDistribution.h"
#include "src/PAnyDistribution.h"
#include "src/PArray.h"
#include "src/PBatch.h"
#include "src/PBeamSmearing.h"
#include "src/PBreitWigner.h"
#include "src/PBulkInterface.h"
#include "src/PChannel.h"
#include "src/PChannelModel.h"
#include "src/PCommandList.h"
#include "src/PComplexBreitWigner.h"
#include "src/PCross.h"
#include "src/PDalitzDecay.h"
#include "src/PDalitzDistribution.h"
#include "src/PData.h"
#include "src/PDataBase.h"
#include "src/PDebugFileOutput.h"
#include "src/PDecayChannel.h"
#include "src/PDecayManager.h"
#include "src/PDeltaAngularDistribution.h"
#include "src/PDiLepton.h"
#include "src/PDistribution.h"
#include "src/PDistributionCollection.h"
#include "src/PDistributionManager.h"
#include "src/PDistributionManagerUtil.h"
#include "src/PDynamicData.h"
#include "src/PEEDirectDecay.h"
#include "src/PEmbeddedParticles.h"
#include "src/PF1.h"
#include "src/PF2.h"
#include "src/PF3.h"
#include "src/PFermiMomentum.h"
#include "src/PFermiMomentumDD.h"
#include "src/PFileInput.h"
#include "src/PFileOutput.h"
#include "src/PFilter.h"
#include "src/PFireball.h"
#include "src/PFixedDecay.h"
#include "src/PFixedProduction.h"
#include "src/PFormula.h"
#include "src/PFunction.h"
#include "src/PGenBod.h"
#include "src/PHadronDecay.h"
#include "src/PHadronDecayM1.h"
#include "src/PHadronDecayM1N.h"
#include "src/PHadronDecayM2.h"
#include "src/PHadronDecayM3.h"
#include "src/PHadronModel.h"
#include "src/PInclusiveModel.h"
#include "src/PIsotropicDistribution.h"
#include "src/PMassSampling.h"
#include "src/PMesh.h"
#include "src/PParticle.h"
#include "src/PPiOmegaAngularDistribution.h"
#include "src/PPlutoBulkDecay.h"
#include "src/PProjector.h"
#include "src/PPropagator.h"
#include "src/PPythiaBulkDecay.h"
#include "src/PReaction.h"
#include "src/PSaid.h"
#include "src/PScatterDistribution.h"
#include "src/PSimpleVMDFF.h"
#include "src/PStaticData.h"
#include "src/PStdData.h"
#include "src/PStdModels.h"
#include "src/PTCrossWeight.h"
#include "src/PThermal.h"
#include "src/PUtils.h"
#include "src/PValues.h"
#include "src/PVertexFile.h"
#include "plugins/nucleus_fermi/PFermiDistributions.h"
#include "plugins/nucleus_fermi/PFermiMomentumGA.h"
#include "plugins/nucleus_fermi/PNucleusFermiPlugin.h"
#include "plugins/pion_beam/PPionBeamPlugin.h"
#include "plugins/pion_beam/PPionBeamAmplitude.h"
#include "plugins/brems/PBremsstrahlung.h"
#include "plugins/brems/PBremsstrahlungPlugin.h"
#include "plugins/hades/PHadesParticleSmearer.h"
#include "plugins/hades/PHGeantOutput.h"
#include "plugins/dalitz_mod/PDalitzModPlugin.h"
#include "plugins/dalitz_mod/PDeltaDalitzFF.h"
#include "plugins/dalitz_mod/PDeltaDalitzKrivoruchenko.h"
#include "plugins/dalitz_mod/PResonanceDalitz.h"
#include "plugins/elementary/PElementaryPlugin.h"
#include "plugins/elementary/PNNFSI.h"
#include "plugins/eta_decays/PEtaDecaysPlugin.h"
#include "plugins/eta_decays/PEtaDoubleDalitz.h"
#include "plugins/eta_decays/PEtaDoubleDalitzFF.h"
#include "plugins/eta_decays/PEtaDoubleDalitzEnv.h"
#include "plugins/eta_decays/PEtaPiPiGamma.h"
#include "plugins/eta_decays/PEtaPiPiDilepton.h"
#include "plugins/eta_decays/PEtaPiPiDileptonMass.h"
#include "plugins/scatter_mod/PSaidLowEnergy.h"
#include "plugins/scatter_mod/PSaidPN.h"
#include "plugins/scatter_mod/PScatterCrossSection.h"
#include "plugins/strangeness/PStrangenessPlugin.h"
#include "plugins/w_decays/POmega3Pi.h"
#include "plugins/pdg_unigen/UEvent.h"
#include "plugins/pdg_unigen/UParticle.h"
#include "plugins/pdg_unigen/URun.h"
#include "plugins/pdg_unigen/PUniGenInput.h"
#include "plugins/pdg_unigen/PPDGPlugin.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__PlutoCintLN_TClass;
extern G__linked_taginfo G__PlutoCintLN_TBuffer;
extern G__linked_taginfo G__PlutoCintLN_TMemberInspector;
extern G__linked_taginfo G__PlutoCintLN_TObject;
extern G__linked_taginfo G__PlutoCintLN_TNamed;
extern G__linked_taginfo G__PlutoCintLN_TString;
extern G__linked_taginfo G__PlutoCintLN_ROOT;
extern G__linked_taginfo G__PlutoCintLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__PlutoCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__PlutoCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PlutoCintLN_TList;
extern G__linked_taginfo G__PlutoCintLN_TObjArray;
extern G__linked_taginfo G__PlutoCintLN_TClonesArray;
extern G__linked_taginfo G__PlutoCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__PlutoCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PlutoCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__PlutoCintLN_TFormula;
extern G__linked_taginfo G__PlutoCintLN_TAttLine;
extern G__linked_taginfo G__PlutoCintLN_TAttFill;
extern G__linked_taginfo G__PlutoCintLN_TAttMarker;
extern G__linked_taginfo G__PlutoCintLN_ROOTcLcLMath;
extern G__linked_taginfo G__PlutoCintLN_ROOTcLcLMathcLcLParamFunctor;
extern G__linked_taginfo G__PlutoCintLN_TF1;
extern G__linked_taginfo G__PlutoCintLN_TH1;
extern G__linked_taginfo G__PlutoCintLN_TMethodCall;
extern G__linked_taginfo G__PlutoCintLN_TLine;
extern G__linked_taginfo G__PlutoCintLN_PAdaptiveMesh;
extern G__linked_taginfo G__PlutoCintLN_TComplex;
extern G__linked_taginfo G__PlutoCintLN_TArrayD;
extern G__linked_taginfo G__PlutoCintLN_TF2;
extern G__linked_taginfo G__PlutoCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__PlutoCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__PlutoCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__PlutoCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__PlutoCintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__PlutoCintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__PlutoCintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__PlutoCintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__PlutoCintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__PlutoCintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__PlutoCintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__PlutoCintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__PlutoCintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__PlutoCintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__PlutoCintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__PlutoCintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__PlutoCintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__PlutoCintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__PlutoCintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__PlutoCintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__PlutoCintLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__PlutoCintLN_TRotation;
extern G__linked_taginfo G__PlutoCintLN_TVector3;
extern G__linked_taginfo G__PlutoCintLN_TLorentzRotation;
extern G__linked_taginfo G__PlutoCintLN_TLorentzVector;
extern G__linked_taginfo G__PlutoCintLN_TFile;
extern G__linked_taginfo G__PlutoCintLN_PDataBase;
extern G__linked_taginfo G__PlutoCintLN_PMesh;
extern G__linked_taginfo G__PlutoCintLN_PStaticData;
extern G__linked_taginfo G__PlutoCintLN_PData;
extern G__linked_taginfo G__PlutoCintLN_PSplash;
extern G__linked_taginfo G__PlutoCintLN_PValues;
extern G__linked_taginfo G__PlutoCintLN_TRandom3;
extern G__linked_taginfo G__PlutoCintLN_TArrayI;
extern G__linked_taginfo G__PlutoCintLN_TH1F;
extern G__linked_taginfo G__PlutoCintLN_PUtilsREngine;
extern G__linked_taginfo G__PlutoCintLN_PUtils;
extern G__linked_taginfo G__PlutoCintLN_PParticle;
extern G__linked_taginfo G__PlutoCintLN_PDistribution;
extern G__linked_taginfo G__PlutoCintLN_PChannelModel;
extern G__linked_taginfo G__PlutoCintLN_PAdaptiveMeshN;
extern G__linked_taginfo G__PlutoCintLN_TGraph;
extern G__linked_taginfo G__PlutoCintLN_TSpline3;
extern G__linked_taginfo G__PlutoCintLN_PAngularDistribution;
extern G__linked_taginfo G__PlutoCintLN_TF3;
extern G__linked_taginfo G__PlutoCintLN_TTree;
extern G__linked_taginfo G__PlutoCintLN_TObjString;
extern G__linked_taginfo G__PlutoCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__PlutoCintLN_PBulkInterface;
extern G__linked_taginfo G__PlutoCintLN_PFormula;
extern G__linked_taginfo G__PlutoCintLN_TH2;
extern G__linked_taginfo G__PlutoCintLN_TH2F;
extern G__linked_taginfo G__PlutoCintLN_TH3;
extern G__linked_taginfo G__PlutoCintLN_TH3F;
extern G__linked_taginfo G__PlutoCintLN_TGraph2D;
extern G__linked_taginfo G__PlutoCintLN_PBatch;
extern G__linked_taginfo G__PlutoCintLN_TNtuple;
extern G__linked_taginfo G__PlutoCintLN_PProjector;
extern G__linked_taginfo G__PlutoCintLN_PAnyDistribution;
extern G__linked_taginfo G__PlutoCintLN_PArray;
extern G__linked_taginfo G__PlutoCintLN_PBeamSmearing;
extern G__linked_taginfo G__PlutoCintLN_PDynamicData;
extern G__linked_taginfo G__PlutoCintLN_PHadronModel;
extern G__linked_taginfo G__PlutoCintLN_PBreitWigner;
extern G__linked_taginfo G__PlutoCintLN_PSaid;
extern G__linked_taginfo G__PlutoCintLN_PStdData;
extern G__linked_taginfo G__PlutoCintLN_PChannel;
extern G__linked_taginfo G__PlutoCintLN_PCommandList;
extern G__linked_taginfo G__PlutoCintLN_PComplexBreitWigner;
extern G__linked_taginfo G__PlutoCintLN_PCross;
extern G__linked_taginfo G__PlutoCintLN_PDalitzDecay;
extern G__linked_taginfo G__PlutoCintLN_PDalitzDistribution;
extern G__linked_taginfo G__PlutoCintLN_PFileOutput;
extern G__linked_taginfo G__PlutoCintLN_PDebugFileOutput;
extern G__linked_taginfo G__PlutoCintLN_PDecayChannel;
extern G__linked_taginfo G__PlutoCintLN_PReaction;
extern G__linked_taginfo G__PlutoCintLN_TPythia6;
extern G__linked_taginfo G__PlutoCintLN_PDistributionCollection;
extern G__linked_taginfo G__PlutoCintLN_PDistributionManagerUtil;
extern G__linked_taginfo G__PlutoCintLN_PDeltaAngularDistribution;
extern G__linked_taginfo G__PlutoCintLN_PScatterDistribution;
extern G__linked_taginfo G__PlutoCintLN_PPiOmegaAngularDistribution;
extern G__linked_taginfo G__PlutoCintLN_PEEDirectDecay;
extern G__linked_taginfo G__PlutoCintLN_PStdModels;
extern G__linked_taginfo G__PlutoCintLN_PDistributionManager;
extern G__linked_taginfo G__PlutoCintLN_PPlutoBulkDecay;
extern G__linked_taginfo G__PlutoCintLN_PFilter;
extern G__linked_taginfo G__PlutoCintLN_PDecayManager;
extern G__linked_taginfo G__PlutoCintLN_PReactionList;
extern G__linked_taginfo G__PlutoCintLN_PNextListlEPChannelgR;
extern G__linked_taginfo G__PlutoCintLN_PNextListlEPParticlegR;
extern G__linked_taginfo G__PlutoCintLN_PNextListlEPParticlemUgR;
extern G__linked_taginfo G__PlutoCintLN_PNextListlEPReactionListgR;
extern G__linked_taginfo G__PlutoCintLN_PDiLepton;
extern G__linked_taginfo G__PlutoCintLN_PEmbeddedParticles;
extern G__linked_taginfo G__PlutoCintLN_PF1;
extern G__linked_taginfo G__PlutoCintLN_PF2;
extern G__linked_taginfo G__PlutoCintLN_PF3;
extern G__linked_taginfo G__PlutoCintLN_PFermiMomentum;
extern G__linked_taginfo G__PlutoCintLN_PFermiMomentumDD;
extern G__linked_taginfo G__PlutoCintLN_PFileInput;
extern G__linked_taginfo G__PlutoCintLN_PFunction;
extern G__linked_taginfo G__PlutoCintLN_PFireball;
extern G__linked_taginfo G__PlutoCintLN_PFixedDecay;
extern G__linked_taginfo G__PlutoCintLN_PFixedProduction;
extern G__linked_taginfo G__PlutoCintLN_PGenBod;
extern G__linked_taginfo G__PlutoCintLN_PHadronDecay;
extern G__linked_taginfo G__PlutoCintLN_PHadronDecayM1;
extern G__linked_taginfo G__PlutoCintLN_TGenPhaseSpace;
extern G__linked_taginfo G__PlutoCintLN_PHadronDecayM1N;
extern G__linked_taginfo G__PlutoCintLN_PHadronDecayM2;
extern G__linked_taginfo G__PlutoCintLN_PHadronDecayM3;
extern G__linked_taginfo G__PlutoCintLN_PInclusiveModel;
extern G__linked_taginfo G__PlutoCintLN_PIsotropicDistribution;
extern G__linked_taginfo G__PlutoCintLN_PMassSampling;
extern G__linked_taginfo G__PlutoCintLN_PPropagator;
extern G__linked_taginfo G__PlutoCintLN_PPythiaBulkDecay;
extern G__linked_taginfo G__PlutoCintLN_PSimpleVMDFF;
extern G__linked_taginfo G__PlutoCintLN_PTCrossWeight;
extern G__linked_taginfo G__PlutoCintLN_PThermal;
extern G__linked_taginfo G__PlutoCintLN_PVertexFile;
extern G__linked_taginfo G__PlutoCintLN_PFermiDistributions;
extern G__linked_taginfo G__PlutoCintLN_PFermiMomentumGA;
extern G__linked_taginfo G__PlutoCintLN_PNucleusFermiPlugin;
extern G__linked_taginfo G__PlutoCintLN_PPionBeamAmplitude;
extern G__linked_taginfo G__PlutoCintLN_PPionBeamPlugin;
extern G__linked_taginfo G__PlutoCintLN_PBremsstrahlung;
extern G__linked_taginfo G__PlutoCintLN_PBremsstrahlungcLcLMode;
extern G__linked_taginfo G__PlutoCintLN_PNNFSI;
extern G__linked_taginfo G__PlutoCintLN_PBremsstrahlungPlugin;
extern G__linked_taginfo G__PlutoCintLN_PHadesParticleSmearer;
extern G__linked_taginfo G__PlutoCintLN_PHGeantOutput;
extern G__linked_taginfo G__PlutoCintLN_PDeltaDalitzKrivoruchenko;
extern G__linked_taginfo G__PlutoCintLN_PDalitzModPlugin;
extern G__linked_taginfo G__PlutoCintLN_PDeltaDalitzFF;
extern G__linked_taginfo G__PlutoCintLN_PResonanceDalitz;
extern G__linked_taginfo G__PlutoCintLN_PElementaryPlugin;
extern G__linked_taginfo G__PlutoCintLN_TRandom2;
extern G__linked_taginfo G__PlutoCintLN_PEtaDoubleDalitz;
extern G__linked_taginfo G__PlutoCintLN_PEtaDoubleDalitzEnv;
extern G__linked_taginfo G__PlutoCintLN_PEtaDoubleDalitzFF;
extern G__linked_taginfo G__PlutoCintLN_PEtaPiPiGamma;
extern G__linked_taginfo G__PlutoCintLN_PEtaDecaysPlugin;
extern G__linked_taginfo G__PlutoCintLN_PEtaPiPiDilepton;
extern G__linked_taginfo G__PlutoCintLN_PEtaPiPiDileptonMass;
extern G__linked_taginfo G__PlutoCintLN_PSaidLowEnergy;
extern G__linked_taginfo G__PlutoCintLN_PSaidPN;
extern G__linked_taginfo G__PlutoCintLN_PScatterCrossSection;
extern G__linked_taginfo G__PlutoCintLN_PStrangenessPlugin;
extern G__linked_taginfo G__PlutoCintLN_POmega3Pi;
extern G__linked_taginfo G__PlutoCintLN_UParticle;
extern G__linked_taginfo G__PlutoCintLN_UEvent;
extern G__linked_taginfo G__PlutoCintLN_TParticle;
extern G__linked_taginfo G__PlutoCintLN_URun;
extern G__linked_taginfo G__PlutoCintLN_PUniGenInput;
extern G__linked_taginfo G__PlutoCintLN_PPDGPlugin;

/* STUB derived class for protected member access */
